export function getAllPosts() {
  return [
    {
      slug: 'first-post',
      title: 'My First Blog Post',
      author: 'dev test',
      category: 'test',
      date: 'Feb 1, 2025',
      imageUrl: 'https://images.pexels.com/photos/346529/pexels-photo-346529.jpeg',
      excerpt: 'lorem ipsum adwiovniopd gdsng anigo di gioand gio goaind ng akn ioda gion giapn diog angdi kano gnoadi digna gid idsf',
      content: 'Here is the full content of the first blog post with more details...',
    },
    {
      slug: 'second-post',
      title: 'MY SECOND BLOG POSTT',
      author: 'dev test',
      category: 'test',
      date: 'Feb 3, 2025',
      imageUrl: 'https://thumbs.dreamstime.com/b/spring-summer-landscape-blue-sky-clouds-river-boat-green-trees-narew-countryside-grass-poland-water-leaves-58070004.jpg',
      excerpt: 'This is the second post yap yuap yap yap yap yap yap yap yap yap yap yap yap',
      content: 'Full guide on making the most out of Next.js with performance tricks...',
    },
    {
      slug: 'third-post',
      title: 'MY thid BLOG POSTT',
      author: 'dev test',
      category: 'test',
      date: 'Feb 5, 2025',
      imageUrl: 'https://www.shutterstock.com/image-photo/spectacular-sunrise-over-scenic-landscape-600nw-2458744877.jpg',
      excerpt: 'This is the thid post yap yuap yap yap yap yap yap yap yap yap yap yap yap',
      content: 'Lorem ipsum odor amet, consectetuer adipiscing elit. Elementum enim iaculis lobortis maecenas lobortis nisi tempor turpis. Fames porta duis inceptos ante maecenas. Dapibus convallis mi per posuere curae urna duis. Nec dictum in dui gravida mollis ullamcorper. Facilisis vulputate dui eleifend vehicula quisque tincidunt laoreet ligula velit. Malesuada lacinia facilisis lacinia venenatis nullam ligula fermentum enim. Consectetur vel eros lobortis sodales mattis convallis aliquam. Lorem tortor himenaeos turpis dignissim facilisis odio eget ridiculus. In aptent felis efficitur vulputate; neque himenaeos urna arcu id.\nLorem ipsum odor amet, consectetuer adipiscing elit. Elementum enim iaculis lobortis maecenas lobortis nisi tempor turpis. Fames porta duis inceptos ante maecenas. Dapibus convallis mi per posuere curae urna duis. Nec dictum in dui gravida mollis ullamcorper. Facilisis vulputate dui eleifend vehicula quisque tincidunt laoreet ligula velit. Malesuada lacinia facilisis lacinia venenatis nullam ligula fermentum enim. Consectetur vel eros lobortis sodales mattis convallis aliquam. Lorem tortor himenaeos turpis dignissim facilisis odio eget ridiculus. In aptent felis efficitur vulputate; neque himenaeos urna arcu id.\nLorem ipsum odor amet, consectetuer adipiscing elit. Elementum enim iaculis lobortis maecenas lobortis nisi tempor turpis. Fames porta duis inceptos ante maecenas. Dapibus convallis mi per posuere curae urna duis. Nec dictum in dui gravida mollis ullamcorper. Facilisis vulputate dui eleifend vehicula quisque tincidunt laoreet ligula velit. Malesuada lacinia facilisis lacinia venenatis nullam ligula fermentum enim. Consectetur vel eros lobortis sodales mattis convallis aliquam. Lorem tortor himenaeos turpis dignissim facilisis odio eget ridiculus. In aptent felis efficitur vulputate; neque himenaeos urna arcu id.',
    },
    {
      slug: 'fourth-post',
      title: 'MY fourth BLOG POSTT',
      author: 'dev test',
      category: 'test',
      date: 'Feb 7, 2025',
      imageUrl: 'https://images.pexels.com/photos/346529/pexels-photo-346529.jpeg',
      excerpt: 'This is the fourth post yap yuap yap yap yap yap yap yap yap yap yap yap yap',
      content: 'Full guide on making the most out of Next.js with performance tricks...',
    },
    {
      slug: 'fifth-post',
      title: 'MY fifth BLOG POSTT',
      author: 'dev test',
      category: 'test',
      date: 'Feb 11, 2025',
      imageUrl: 'https://images.pexels.com/photos/346529/pexels-photo-346529.jpeg',
      excerpt: 'This is the fifth post yap yuap yap yap yap yap yap yap yap yap yap yap yap',
      content: 'Full guide on making the most out of Next.js with performance tricks...',
    },
    {
      slug: 'sixth-post',
      title: 'MY sixth BLOG POSTT',
      author: 'dev test',
      category: 'test',
      date: 'Feb 3, 2025',
      imageUrl: 'https://images.pexels.com/photos/346529/pexels-photo-346529.jpeg',
      excerpt: 'This is the sixth post yap yuap yap yap yap yap yap yap yap yap yap yap yap',
      content: 'Full guide on making the most out of Next.js with performance tricks...',
    },
    {
      slug: 'seventth-post',
      title: 'MY seventh BLOG POSTT',
      author: 'dev test',
      category: 'test',
      date: 'Feb 3, 2025',
      imageUrl: 'https://images.pexels.com/photos/346529/pexels-photo-346529.jpeg',
      excerpt: 'This is the seventh post yap yuap yap yap yap yap yap yap yap yap yap yap yap',
      content: 'Full guide on making the most out of Next.js with performance tricks...',
    },

  ];
}